services:
  db:
    image: postgres:15
    container_name: tyson-db
    environment:
      POSTGRES_DB: tyson-local-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tyson-local-db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  default:
    name: my-network
